apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    tier: backend
    type: volume
  name: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
  storageClassName: local-storage
