apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiv1
  template:
    metadata:
      labels:
        type: api
        tier: backend
        app: apiv1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - external
      containers:
      - image: public-registry.caliopen.org/caliopen_apiv1
        imagePullPolicy: Always
        name: apiv1
        ports:
        - containerPort: 6543
        volumeMounts:
        - name: apiv1-conf-volume
          mountPath: /etc/caliopen/apiv1.ini
          subPath: apiv1.ini
        - name: caliopen-conf-volume
          mountPath: /etc/caliopen/caliopen.yaml
          subPath: caliopen.yaml
        - name: swagger-conf-volume
          mountPath: /etc/caliopen/swagger.json
          subPath: swagger.json
      volumes:
      - name: apiv1-conf-volume
        configMap:
          name: apiv1-config
          items:
          - key: apiv1.ini
            path: apiv1.ini
      - name: caliopen-conf-volume
        configMap:
          name: caliopen-config
          items:
          - key: caliopen.yaml
            path: caliopen.yaml
      - name: swagger-conf-volume
        configMap:
          name: swagger-config
          items:
          - key: swagger.json
            path: swagger.json
      restartPolicy: Always
