apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiv2
  #strategy:
  #  type: RollingUpdate
  #    maxUnavailable: 50
  template:
    metadata:
      labels:
        type: api
        tier: backend
        app: apiv2
    spec:
      containers:
      - image: public-registry.caliopen.org/caliopen_api
        imagePullPolicy: Always
        name: apiv2
        ports:
        - containerPort: 31415
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: apiv2.yaml
            path: apiv2.yaml
          - key: swagger.json
            path: swagger.json
      restartPolicy: Always
