apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  #strategy:
  #  type: RollingUpdate
  #    maxUnavailable: 50
  template:
    metadata:
      labels:
        type: frontend
        tier: frontend
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - external
      containers:
      - image: public-registry.caliopen.org/caliopen_frontend:develop
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 4000
        env:
        - name: CALIOPEN_API_HOSTNAME
          value: "api.beta.caliopen.org"
        - name: CALIOPEN_API_PROTOCOL
          value: "https"
        - name: CALIOPEN_API_PORT
          value: "443"
      restartPolicy: Always
