apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity_poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity_poller
  #strategy:
  #  type: RollingUpdate
  #    maxUnavailable: 50
  template:
    metadata:
      labels:
        type: identity_poller
        tier: remote-identities
        app: identity_poller
    spec:
      containers:
      - image: public-registry.caliopen.org/caliopen_identity_poller
        imagePullPolicy: Always
        name: identity_poller
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: caliopen-IDs-poller.yaml
            path: caliopen-IDs-poller.yaml
      restartPolicy: Always
