apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmtpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmtpd
  #strategy:
  #  type: RollingUpdate
  #    maxUnavailable: 50
  template:
    metadata:
      labels:
        type: lmtp
        tier: backend
        app: lmtpd
    spec:
      containers:
      - image: public-registry.caliopen.org/caliopen_broker:develop
        imagePullPolicy: Always
        name: lmtpd
        ports:
        - containerPort: 2525
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: lmtp.yaml
            path: lmtp.yaml
      restartPolicy: Always
