apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-handler
  #strategy:
  #  type: RollingUpdate
  #    maxUnavailable: 50
  template:
    metadata:
      labels:
        type: message-handler
        tier: backend
        app: message-handler
    spec:
      containers:     
      - image: public-registry.caliopen.org/caliopen_message-handler
        imagePullPolicy: Always
        name: message-handler
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: caliopen.yaml
            path: caliopen.yaml
      restartPolicy: Always
