apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-worker
  #strategy:
  #  type: RollingUpdate
  #    maxUnavailable: 50
  template:
    metadata:
      labels:
        type: mq-worker
        tier: backend
        app: mq-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - internal
      containers:     
      - image: public-registry.caliopen.org/caliopen_message_handler:develop
        imagePullPolicy: Always
        name: mq-worker
        volumeMounts:
        - name: config-volume
          mountPath: /etc/caliopen
      volumes:
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: caliopen.yaml
            path: caliopen.yaml
      restartPolicy: Always
