apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-worker
  template:
    metadata:
      labels:
        type: twitter-worker
        tier: worker
        app: twitter-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - internal
      containers:
      - image: public-registry.caliopen.org/caliopen_twitter_worker
        imagePullPolicy: Always
        name: twitter-worker
        volumeMounts:
        - name: twitterworker-conf-volume
          mountPath: /etc/caliopen/twitterworker.yaml
          subPath: twitterworker.yaml
        - name: ca-certs
          mountPath: /etc/ssl/certs
      volumes:
      - name: twitterworker-conf-volume
        configMap:
          name: twitterworker-config
          items:
          - key: twitterworker.yaml
            path: twitterworker.yaml
      - name: ca-certs
        configMap:
          name: ca-certs
          items:
          - key: alpha.caliopen.org.crt
            path: alpha.caliopen.org.crt
          - key: beta.caliopen.org.crt
            path: beta.caliopen.org.crt
          - key: ca-certificates.crt
            path: ca-certificates.crt
      restartPolicy: Always
