- name: install haproxy
  apt: package={{ item }} state=installed update_cache=yes
  with_items:
    - haproxy

- name: copy config file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: install ssl certificate and private key
  copy: src={{ item }} dest=/etc/haproxy/certs/{{ item }}
  with_items:
    - "{{ caliopen_domain_name }}.crt"
    - "{{ caliopen_domain_name }}.key"

- name: create pem file
  shell: cat {{ caliopen_domain_name }}.crt {{ caliopen_domain_name }}.key > alpha-certs.pem

- name: restart haproxy service
  shell: service haproxy restart
