# VM configuration

##Common
image: Ubuntu 16.04 LTS
vlan_name: kube_vlan
base_net: 192.168.1
vlan_net: "{{ base_net }}.0/24"
datacenter: FR-SD5

#Cluster nodes, including master
node_cpu: 2
node_mem: 4096
node_disk: 20

# IP addresses
master_ip: "{{ base_net }}.1"
node_0_ip: "{{ base_net }}.2"
node_1_ip: "{{ base_net }}.3"
node_2_ip: "{{ base_net }}.4"
node_3_ip: "{{ base_net }}.5"

#SSH keys
#You can give a key id
gandi_ssh_key_id: 41934
