- hosts: gw
  become: yes
  remote_user: root
  roles:
    - kube
  tags:
    - infra
    - bastion

- hosts: master_node
  become: yes
  remote_user: root
  roles:
    - common
    - docker
    - kube
    - master
  tags: infra

- hosts: worker_node
  become: yes
  remote_user: root
  roles:
    - common
    - docker
    - kube
    - worker
  tags: infra

- hosts: master_node
  become: yes
  remote_user: root
  roles:
    - caliopen
  tags: application
