- hosts: lb
  become: yes
  remote_user: root
  roles:
    - common
    - kube
    - lb
    - gateway
  tags:
    - infra
    - bastion

- hosts: master
  become: yes
  remote_user: root
  roles:
    - common
    - docker
    - kube
    - master
  tags: infra

- hosts: worker
  become: yes
  remote_user: root
  roles:
    - common
    - docker
    - kube
    - worker
  tags: infra

- hosts: master
  become: yes
  remote_user: root
  roles:
    - caliopen
    - monitoring
  tags: application
