- name: delete deployment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "vm_vars/credentials.yaml"
    - "vm_vars/settings.yaml"

  tasks:
  - name: delete bastion
    gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      instance_names: bastion
      datacenter: "{{ datacenter }}"
      state: deleted
    tags: bastion

  - name: delete all nodes
    gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      name: "{{ item }}"
      datacenter: "{{ datacenter }}"
      state: deleted
    with_items:
      - master
      - node0
      - node1
      - node2
      - node3
    tags: kube_cluster
    async: 7200
    poll: 0
    register: node_deletion

  - name: wait for deletion
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: jobs
    until: jobs.finished
    delay: 10
    retries: 300
    with_items:
      - "{{ node_deletion.results }}"

  - gandi_vlan:
      gandi_api_key: "{{ gandi_api_key }}"
      name: "{{ vlan_name }}"
      datacenter: "{{ datacenter }}"
      state: deleted
    tags: vlan
    name: delete vlan
