- name: delete deployment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "vm_vars/credentials.yaml"
    - "vm_vars/settings.yaml"

  tasks:
  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      instance_names: bastion
      datacenter: "{{ datacenter }}"
      state: deleted
    tags: bastion

  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      instance_names: node,node0,node1,node2,node3,node4,master,master0,master1,master2
      datacenter: "{{ datacenter }}"
      state: deleted
    tags: kube_cluster

  - gandi_vlan:
      gandi_api_key: "{{ gandi_api_key }}"
      name: "{{ vlan_name }}"
      datacenter: "{{ datacenter }}"
      state: deleted
    tags: vlan
