- name: delete deployment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "vm_vars/credentials.yaml"
    - "vm_vars/settings.yaml"

  tasks:
  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      name: nodetest
      datacenter: "{{ datacenter }}"
      state: deleted
    tags: one

  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      instance_names: node,node0,node1,node2,node3,node4,master,master0,master1,master2,bastion
      datacenter: "{{ datacenter }}"
      state: deleted

  - gandi_vlan:
      gandi_api_key: "{{ gandi_api_key }}"
      name: "{{ vlan_name }}"
      datacenter: "{{ datacenter }}"
      state: deleted

