- name: test-deployment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "vm_vars/credentials.yaml"
    - "vm_vars/settings.yaml"

  tasks:
  - gandi_vlan:
      gandi_api_key: "{{ gandi_api_key }}"
      name: "{{ vlan_name }}"
      datacenter: "{{ datacenter }}"
      gateway: "{{ bastion_ip }}"
      subnet: "{{ vlan_net }}"
    tags: vlan

  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      name: bastion
      machine_type: custom
      image: "{{ image }}"
      datacenter: "{{ datacenter }}"
      sshkey_ids: [{{ gandi_ssh_key_id }}]
      cores: "{{ bastion_cores }}"
      memory: "{{ bastion_memory }}"
      disk: "{{ bastion_disk }}"
      interfaces: {'publics': [{'ipv4': 'auto'}], 'privates': [{'vlan': "{{ vlan_name }}", 'ipv4': "{{ bastion_ip }}"}]}
      state: running
      farm: bastion_node
    tags: bastion

  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      name: master
      machine_type: custom
      image: "{{ image }}"
      datacenter: "{{ datacenter }}"
      sshkey_ids: [{{ gandi_ssh_key_id }}]
      cores: "{{ node_cpu }}"
      memory: "{{ node_mem }}"
      disk: "{{ node_disk }}"
      interfaces: {'privates': [{'vlan': "{{ vlan_name }}", 'ipv4': "{{ master_ip }}"}]}
      state: running
      farm: master_node
    tags:
      - master
      - kube_cluster

  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      name: node0
      image: "{{ image }}"
      machine_type: custom
      datacenter: "{{ datacenter }}"
      sshkey_ids: [{{ gandi_ssh_key_id }}]
      cores: "{{ node_cpu }}"
      memory: "{{ node_mem }}"
      disk: "{{ node_disk }}"
      extra_disks: [{'name': 'db0', 'size': {{ cassandra_disk }}}, {'name': 'index0', 'size': {{ elasticsearch_disk }}}, {'name': 'store0', 'size': {{ minio_disk }}}]
      interfaces: {'privates': ['vlan': "{{ vlan_name }}"]}
      state: running
      farm: worker_node
    tags:
      - worker
      - kube_cluster

  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      name: node1
      image: "{{ image }}"
      machine_type: custom
      datacenter: "{{ datacenter }}"
      sshkey_ids: [{{ gandi_ssh_key_id }}]
      cores: "{{ node_cpu }}"
      memory: "{{ node_mem }}"
      disk: "{{ node_disk }}"
      extra_disks: [{'name': 'db1', 'size': {{ cassandra_disk }}}, {'name': 'index1', 'size': {{ elasticsearch_disk }}}, {'name': 'store1', 'size': {{ minio_disk }}}]
      interfaces: {'privates': ['vlan': "{{ vlan_name }}"]}
      state: running
      farm: worker_node
    tags:
      - worker
      - kube_cluster

  - gandi_vps:
      gandi_api_key: "{{ gandi_api_key }}"
      name: node2
      image: "{{ image }}"
      machine_type: custom
      datacenter: "{{ datacenter }}"
      sshkey_ids: [{{ gandi_ssh_key_id }}]
      cores: "{{ node_cpu }}"
      memory: "{{ node_mem }}"
      disk: "{{ node_disk }}"
      extra_disks: [{'name': 'db2', 'size': {{ cassandra_disk }}}, {'name': 'index2', 'size': {{ elasticsearch_disk }}}, {'name': 'store2', 'size': {{ minio_disk }}}]
      interfaces: {'privates': ['vlan': "{{ vlan_name }}"]}
      state: running
      farm: worker_node
    tags:
      - worker
      - kube_cluster