apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: 3
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        # env:
        # - name: MINIO_ACCESS_KEY
        #   value: "GWEDQM67MIQ2E5QGV8O8" # NOT THE ACTUAL ACCESS KEY
        # - name: MINIO_SECRET_KEY
        #   value: "Iws33XVjElFFbCfDqpoPbMvktCZsAOCC7FivMKTg" # NOT THE ACTUAL SECRET KEY
        image: minio/minio
        args:
        - server
        - http://minio-0.minio.default.svc.cluster.local/export
        - http://minio-1.minio.default.svc.cluster.local/export
        - http://minio-2.minio.default.svc.cluster.local/export
        - http://minio-3.minio.default.svc.cluster.local/export
        - --address
        - :9090
        - -C
        - /configs/minio
        - /export
        ports:
        - containerPort: 9090
        # These volume mounts are persistent. Each pod in the PetSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - mountPath: /export
          name: store
        - mountPath: /configs/minio/config.json
          name: config-volume
          subPath: config.json
      volumes:
      - name: store
        persistentVolumeClaim:
          claimName: store
      - name: config-volume
        configMap:
          name: caliopen-config
          items:
          - key: config.json
            path: config.json
