apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "CALIOPEN_ACCESS_KEY_" # NOT THE ACTUAL ACCESS KEY
        - name: MINIO_SECRET_KEY
          value: "CALIOPEN_SECRET_KEY_BE_GOOD_AND_LIVE_OLD" # NOT THE ACTUAL SECRET KEY
        image: minio/minio
        args:
        - server
        - --address
        - :9090
        - -C
        - /configs/minio
        - /export
        ports:
        - containerPort: 9090
        # These volume mounts are persistent. Each pod in the PetSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - mountPath: /export
          name: store
  volumeClaimTemplates:
  - metadata:
      name: store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: minio-storage
      resources:
        requests:
          storage: 5Gi