---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: monitoring
  labels:
    app: logstash
data:
  logstash.yml: |-
    node.name: logstash
    path.config: /usr/share/logstash/pipeline
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        tier: monitoring
        app: logstash
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - internal
      terminationGracePeriodSeconds: 30
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:5.6.12
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP      
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          readOnly: true
          subPath: logstash.yml
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: logstash-config
      - name: pipeline
        configMap:
          name: logstash-pipeline

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: monitoring
  labels:
    app: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    nodePort: 30544
    protocol: TCP
