- name: Ensures /etc/logstash dir exists
  file: path=/etc/logstash state=directory
  tags: logstash

- name: copy logstash configs
  template:
    src: "{{ item }}"
    dest: "/etc/logstash"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "templates/*"
  tags: logstash

- name: create logstash pipeline
  shell: kubectl create configmap logstash-pipeline --from-file=/etc/logstash/logstash.conf -n monitoring
  tags: logstash
