- name: copy logstash config
  template:
    src: "templates/logstash.conf"
    dest: "/etc/caliopen"
    owner: "root"
    mode: 0600
  tags: logstash

- name: create logstash pipeline
  shell: kubectl create configmap logstash-pipeline --from-file=/etc/caliopen/logstash.conf -n monitoring
  tags: logstash
