---
- name: create namespace monitoring
  shell: kubectl create namespace monitoring

- name: create dashboard
  shell: kubectl apply -f {{ yaml_url }}/monitoring/{{ item }}.yaml
  with_items:
    - dashboard
  tags: dashboard

- import: config_pipeline.yml

- name: create logging deployments
  shell: kubectl apply -f {{ yaml_url }}/monitoring/{{ item }}.yaml -n monitoring
  with_items:
    - filebeat
    - logstash
  tags: logging

# - name: create monitoring deployments
#   shell: kubectl apply -f {{ yaml_url }}/monitoring/{{ item }}.yaml -n {{ prod_namespace }}
#   with_items:
#     - prometheus
#   tags: monitoring
