apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  selector:
    app: cassandra
  ports:
  - port: 9042
    name: "cql"
  - port: 9160
    name: "thrift"
  - port: 7000
    name: "intra-node"
