apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    nodePort: 30443
    port: 443
    targetPort: 443
    protocol: TCP
  - name: health
    nodePort: 30880
    port: 18080
    targetPort: 18080
  - name: lmtp
    nodePort: 32525
    port: 2525
    targetPort: 2525
    protocol: TCP
  selector:
    app: ingress-nginx
