---

- name: Copy amavis configuration
  template:
    src: amavis/{{ item }}.j2
    dest: /etc/amavis/conf.d/{{ item }}
    mode: 0770
  with_items:
    - "05-node_id"
    - "50-user"

- name: Install amavis
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - amavisd-new
    - amavisd-milter
    - libdbi-perl

- name: Configure Amavis Socket
  template:
    src: amavis/amavisd-milter.j2
    dest: /etc/default/amavisd-milter
  notify:
    - restart amavisd-milter


- name: Add postfix to amavis group
  user:
    name: postfix
    groups: amavis
    append: yes
  notify:
    - restart postfix
