---
- include: namespaces_labels.yml

- include: certs.yml

- include: configs.yml

- name: create go app deployments
  shell: kubectl apply -f {{ yaml_url }}/caliopen_services/{{ item }}.yaml -n {{ kube_namespace }}
  with_items:
    - lmtpd
    - apiv2
    - identity-poller
    - imap-worker
    - twitter-worker
  tags: [ go, deployment ]

- name: create python app deployments
  shell: kubectl apply -f {{ yaml_url }}/caliopen_services/{{ item }}.yaml -n {{ kube_namespace }}
  with_items:
    - mq-worker
    - apiv1
  tags: [ python, deployment ]

- name: create frontend app deployments
  shell: kubectl apply -f {{ yaml_url }}/caliopen_services/{{ item }}.yaml -n {{ kube_namespace }}
  with_items:
    - frontend
  tags: [ frontend, deployment ]
