- name: Ensures {{ caliopen_config_path }} dir exists
  file: path={{ caliopen_config_path }} state=directory

- name: copy caliopen configs
  copy:
    src: "{{ item }}"
    dest: "{{ caliopen_config_path }}"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "templates/configs/*"

- name: create caliopen configs
  shell: kubectl create configmap caliopen-config --from-file={{ caliopen_config_path }}
  ignore_errors: yes

- name: create services
  shell: kubectl apply -f {{ yaml_url }}/services/{{ item }}-service.yaml
  with_items:
    - apiv2
    - apiv1
    - broker
    - frontend
  tags: service

- name: create go app deployments
  shell: kubectl apply -f {{ yaml_url }}/deployments/{{ item }}-deployment.yaml
  with_items:
    - lmtpd
    - apiv2
    - identity-poller
    - identity-worker
  tags: [ go, deployment ]

- name: create python app deployments
  shell: kubectl apply -f {{ yaml_url }}/deployments/{{ item }}-deployment.yaml
  with_items:
    - message-handler
    - apiv1
  tags: [ python, deployment ]

- name: create frontend app deployments
  shell: kubectl apply -f {{ yaml_url }}/deployments/{{ item }}-deployment.yaml
  with_items:
    - frontend
  tags: [ frontend, deployment ]

- name: create dashboard service
  shell: kubectl apply -f {{ yaml_url }}/services/{{ item }}-service.yaml
  with_items:
    - dashboard
  tags: service
