# Caliopen configuration file to run REST API server in a docker container
#
# Storage services must be accessible using FQDN:
#  - cassandra.dev.caliopen.org
#  - es.dev.caliopen.org
#  - redis.dev.caliopen.org (see pyramid configuration file)
#
# Make your /etc/hosts lie or user docker containers from docker-compose.yml in /devtools

delivery_agent:
    direct: True

elasticsearch:
    url:
{% for host in groups['store'] %}
      - http://{{ hostvars[host]['private_ips'][0] }}:9200
{% endfor %}
    mappings_version: v6
    shards:
        - caliopen-prod-00000001
        - caliopen-prod-00000002
        - caliopen-prod-00000003
        - caliopen-prod-00000004
        - caliopen-prod-00000005
        - caliopen-prod-00000006
        - caliopen-prod-00000007
        - caliopen-prod-00000008
        - caliopen-prod-00000009
        - caliopen-prod-00000010
        - caliopen-prod-00000011
        - caliopen-prod-00000012
        - caliopen-prod-00000013
        - caliopen-prod-00000014
        - caliopen-prod-00000015
        - caliopen-prod-00000016
        - caliopen-prod-00000017
        - caliopen-prod-00000018
        - caliopen-prod-00000019
        - caliopen-prod-00000020


cassandra:
    keyspace: {{ caliopen_cassandra_keyspace }}
    hosts:
{% for host in groups['store'] %}
      - {{ hostvars[host]['private_ips'][0] }}
{% endfor %}
    consistency_level: 1
    protocol_version: 3

lmtp:
    port: 4025
    bind_address: 0.0.0.0

broker:
    port: 2525
    host: lmtpd

message_queue:
    port: 4222
    host: {{ nats_host }}

object_store:
    db_size_limit: 1048576
    service: s3
    endpoint: {{ object_store_host }}:9000
    access_key: {{ object_store_access_key }}
    secret_key: {{ object_store_secret_key }}
    location: eu-fr-paris
    buckets:
        raw_messages: {{ caliopen_bucket_raw_message }}
        temporary_attachments: {{ caliopen_bucket_tmp_attachment }}
        learn_models: {{ caliopen_bucket_learn_model }}

system:
    default_tags:
        -
            name: inbox
        -
            name: spam
        -
            name: important
            importance_level: 5
        -
            name: internal
            label: Caliopen
            importance_level: 2

default_domain: {{ caliopen_domain_name }}

internal_domains:
    - {{ caliopen_domain_name }}

blacklistes:
    mx:
        - mx.bad.guy

qualifiers:
    geoip:
        file: "/var/lib/geoip2/GeoLite2-Country.mmdb"

apiV1:
    strict_patch: false

key_discovery:
    dns:
        enable: False
        name_server: 4.4.4.4
    hkp:
        enable: True
        url: https://pgp.mit.edu/pks/lookup
