# Caliopen configuration file to run REST API server in a docker container
#
# Storage services must be accessible using FQDN:
#  - cassandra.dev.caliopen.org
#  - es.dev.caliopen.org
#  - redis.dev.caliopen.org (see pyramid configuration file)
#
# Make your /etc/hosts lie or user docker containers from docker-compose.yml in /devtools

delivery_agent:
    direct: True

elasticsearch:
    url: http://elasticsearch:9200
    mappings_version: v5

cassandra:
    keyspace: caliopen
    hosts:
{% for host in groups['store'] %}
      - {{ hostvars[host]['backend_ip'] }}
{% endfor %}
    consistency_level: 1
    protocol_version: 3

lmtp:
    port: 4025
    bind_address: 0.0.0.0

broker:
    port: 2525
    host: broker

message_queue:
    port: 4222
    host: nats

object_store:
    db_size_limit: 1048576
    service: s3
    endpoint: {{ hostvars['object_store1']['backend_ip'] }}:9000
    access_key: {{ object_store_access_key }}
    secret_key: {{ object_store_secret_key }}
    location: eu-fr-paris

system:
    max_users: 100
    default_tags:
        -
            name: inbox
        -
            name: spam
        -
            name: important
            importance_level: 5
        -
            name: internal
            label: Caliopen
            importance_level: 2

default_domain: caliopen.local

internal_domains:
    - caliopen.local
    - brainstorm.fr

blacklistes:
    mx:
        - mx.bad.guy

key_discovery:
    dns:
        enable: True
        name_server: 8.8.8.8
