workers: 2                                             # number of concurrent workers
#messaging system
nats_url: nats://{{ hostvars['mq1']['backend_ip'] }}:4222
nats_queue: IMAPworkers                                # NATS group queue for workers
nats_topic: IMAPfetcher                                # NATS topic to listen to actions to execute
#storage facility
store_name: cassandra                                  # backend to store raw emails and messages (inbound & outbound)
store_settings:
  hosts: # many allowed
{% for host in groups['store'] %}
    - {{ hostvars[host]['backend_ip'] }}
{% endfor %}
  keyspace: caliopen
  consistency_level: 1
  raw_size_limit: 1048576                                 # max size in bytes for objects in db. Use S3 interface if larger.
  object_store: s3
  object_store_settings:
    endpoint: {{ hostvars['object_store1']['backend_ip'] }}:9000
    access_key: {{ object_store_access_key }}
    secret_key: {{ object_store_secret_key }}
    location: eu-fr-paris
    buckets:
      raw_messages: caliopen-raw-messages                # bucket name to put raw messages to
      temporary_attachments: caliopen-tmp-attachments    # bucket name to store draft attachments
  use_vault: true
  vault_settings:
    url: https://vault.{{ caliopen_domain_name }}:8200
    username: {{ vault_api_username }}
    password: {{ vault_api_password }}
LDAConfig:
  broker_type: imap                                      # types are : smtp, imap, mailboxe, etc.
  lda_workers_size: 2                                    # number of concurrent workers
  log_received_mails: true
  #index facility
  index_name: elasticsearch                              # backend to index messages (inbound & outbound)
  index_settings:
    urls: # many allowed
{% for host in groups['store'] %}
      - http://{{ hostvars[host]['backend_ip'] }}:9200
{% endfor %}
  #messaging system
  in_topic: inboundSMTP # NATS topic to listen to
  nats_queue: SMTPqueue
  # notifications
  NotifierConfig:
    admin_username: admin                                # username on whose behalf notifiers will act. This admin user must have been created before by other means.
