- name: turn off swap
  command: swapoff -a

- name: install node exporter service
  template: src=node-exporter.service.j2 dest=/etc/systemd/system/node-exporter.service
  tags: node-exporter

- name: start node-exporter service
  service:
    name: node-exporter
    state: started

- name: install kube utilities
  apt: package={{ item }} update_cache=yes
  with_items:
    - kubelet
    - kubeadm

- name: reset before join
  command: kubeadm reset --force
  when: kubeadm_reset

- name: join k8s cluster
  command: kubeadm join --token {{ kube_token }} {{ master_private_ip }}:6443 --discovery-token-unsafe-skip-ca-verification
