- name: turn off swap
  command: swapoff -a

- name: install kube utilities
  apt:
    package: "{{ item }}"
    update_cache: yes
  with_items:
    #- kubernetes-cni=0.6.0-00 # Temporary requirement if using kubernetes version 1.13.2
    - kubeadm={{ kubernetes_version }}
    - kubelet={{ kubernetes_version }}

- name: reset before join
  command: kubeadm reset --force
  when: kubeadm_reset

- name: join k8s cluster
  command: kubeadm join --token {{ kube_token }} {{ master_private_ip }}:6443 --discovery-token-unsafe-skip-ca-verification
