{
 "title": "Cluster services",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "LB frontend sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions) by (frontend)"
    }
   ]
  },
  {
   "title": "Stores cpu load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"external nodes\", instance=~\"192.168.1.1[0-9].*\"}"
    }
   ]
  },
  {
   "title": "HTTP Invalid responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_requests{status!~\"[23].{2}\"}) by(ingress, status)"
    }
   ]
  },
  {
   "title": "Nats messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gnatsd_varz_out_msgs[1m])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Cpu per service (without apiv1)",
   "type": "graph",
   "description": "All production applications CPU",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{namespace=\"production\", pod_name!~\"^apiv1.*\", container_name!=\"\"}[1m])) by (container_name)"
    }
   ]
  },
  {
   "title": "Memory per service",
   "type": "graph",
   "description": "All production applications CPU",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"production\", pod_name!~\"^apiv1.*\", container_name!=\"\"}[5m])) by (container_name)"
    }
   ]
  },
  {
   "title": "Nats connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatsd_connz_num_connections" }
   ]
  },
  {
   "title": "Cache keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_db_keys{db=\"db0\"}"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(go_goroutines) by (job)" }
   ]
  },
  {
   "title": "Redis clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_connected_clients[1m])"
    }
   ]
  }
 ]
}