- name: install dependencies
  apt:
    package: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
    filename: docker
    state: present

- name: install docker ce
  apt:
    package: "{{ item }}"
    update_cache: yes
  with_items:
    - docker-ce={{ docker_version }}

- name: add user to group docker
  command: usermod -aG docker {{ ansible_user }}

- name: start docker
  service:
    name: docker
    state: restarted
