groups:
- name: roles/monitoring/files/alertmanager_rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} down
  - alert: FilesystemFull
    expr: node_filesystem_free / node_filesystem_size < 0.3
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} free space less
        than 30%.'
      summary: Filesystem {{ $labels.instance }} full
