apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  #strategy:
  #  type: RollingUpdate
  #    maxUnavailable: 50
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - external
      containers:
      - image: public-registry.caliopen.org/caliopen_frontend
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 4000
        env:
        - name: CALIOPEN_API_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api_hostname
        - name: CALIOPEN_API_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api_protocol
        - name: CALIOPEN_API_PORT
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api_port
        - name: CALIOPEN_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: webserver_hostname
              name: frontend-config
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - name: "frontend"
    port: 4000
    targetPort: 4000
    nodePort: 30400
