apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-poller
  template:
    metadata:
      labels:
        type: identity-poller
        tier: remote-identities
        app: identity-poller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - internal
      terminationGracePeriodSeconds: 180
      containers:
      - image: public-registry.caliopen.org/caliopen_identity_poller
        imagePullPolicy: Always
        name: identity-poller
        volumeMounts:
        - name: idpoller-conf-volume
          mountPath: /etc/caliopen/idpoller.yaml
          subPath: idpoller.yaml
      volumes:
      - name: idpoller-conf-volume
        configMap:
          name: idpoller-config
          items:
          - key: idpoller.yaml
            path: idpoller.yaml
      restartPolicy: Always
