apiVersion: apps/v1
kind: Deployment
metadata:
  name: imap-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imap-worker
  template:
    metadata:
      labels:
        type: imap-worker
        tier: remote-identities
        app: imap-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - internal
      terminationGracePeriodSeconds: 180
      containers:
      - image: public-registry.caliopen.org/caliopen_imap_worker
        imagePullPolicy: Always
        name: imap-worker
        volumeMounts:
        - name: imapworker-conf-volume
          mountPath: /etc/caliopen/imapworker.yaml
          subPath: imapworker.yaml
        - name: ca-certs
          mountPath: /etc/ssl/certs
      volumes:
      - name: imapworker-conf-volume
        configMap:
          name: imapworker-config
          items:
          - key: imapworker.yaml
            path: imapworker.yaml
      - name: ca-certs
        configMap:
          name: ca-certs
          items:
          - key: alpha.caliopen.org.crt
            path: alpha.caliopen.org.crt
          - key: beta.caliopen.org.crt
            path: beta.caliopen.org.crt
          - key: ca-certificates.crt
            path: ca-certificates.crt
      restartPolicy: Always
