apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmtpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmtpd
  template:
    metadata:
      labels:
        type: lmtp
        tier: backend
        app: lmtpd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - internal
      containers:
      - image: public-registry.caliopen.org/caliopen_lmtpd
        imagePullPolicy: Always
        name: lmtpd
        ports:
        - containerPort: 2525
        volumeMounts:
        - name: lmtp-conf-volume
          mountPath: /etc/caliopen/lmtp.yaml
          subPath: lmtp.yaml
      volumes:
      - name: lmtp-conf-volume
        configMap:
          name: lmtp-config
          items:
          - key: lmtp.yaml
            path: lmtp.yaml
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: lmtpd
spec:
  selector:
    app: lmtpd
  type: NodePort
  ports:
  - name: "lmtpd"
    port: 2525
    targetPort: 2525
    nodePort: 32525
