apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-worker
  template:
    metadata:
      labels:
        type: mastodon-worker
        tier: worker
        app: mastodon-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - internal
      terminationGracePeriodSeconds: 180
      containers:
      - image: public-registry.caliopen.org/caliopen_mastodonworker
        imagePullPolicy: Always
        name: mastodon-worker
        volumeMounts:
        - name: mastodonworker-conf-volume
          mountPath: /etc/caliopen/mastodonworker.yaml
          subPath: mastodonworker.yaml
        - name: ca-certs
          mountPath: /etc/ssl/certs
      volumes:
      - name: mastodonworker-conf-volume
        configMap:
          name: mastodonworker-config
          items:
          - key: mastodonworker.yaml
            path: mastodonworker.yaml
      - name: ca-certs
        configMap:
          name: ca-certs
          items:
          - key: alpha.caliopen.org.crt
            path: alpha.caliopen.org.crt
          - key: beta.caliopen.org.crt
            path: beta.caliopen.org.crt
          - key: ca-certificates.crt
            path: ca-certificates.crt
      restartPolicy: Always
