---
# django like formatting for string blocks
# fields available within template blocks :
#   - user's given_name => given_name
#   - user's family_name => family_name
#   - instance domain name => domain
#   - url of the reset password link => url

subject: "Demande de réinitialisation de votre mot de passe"
body_plain: "\n
Bonjour {{ given_name }} {{ family_name }},\n
nous avons pris note d'une demande de réinitialisation de votre mot de passe sur {{ domain }}.\n
Pour le réinitialiser, veuillez cliquer sur ce lien :\n
\n
{{ url }}\n
\n
et suivre les indications à l'écran.\n
\n
Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer ce mail.\n
\n
Cordialement,\n
L'équipe de Caliopen.\n
"
